spring:
  http:
    encoding:
      charset:    UTF-8
  mvc:
    view:
      prefix:     /jsp/
      suffix:     .jsp
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081

rssportal:
  vftp:
    directory:
      request: testroot/VFTPREQUEST02
    objectlistfile: testroot/CanonFileService02/definitions/ObjectList.xml
  property:
    constructdisplay: devTemp/ConstructDisplay.xml
  collect:
    logBase: planroot
    cacheBase: download
    
