spring:
  http:
    encoding:
      charset:    UTF-8
  mvc:
    view:
      prefix:     /jsp/
      suffix:     .jsp
server:
  tomcat:
    uri-encoding: UTF-8

rssportal:
  vftp:
    directory:
      request: /LOG/VFTP/Requests
    objectlistfile: /usr/local/canon/esp/CanonFileService/definitions.ObjectList.xml