log4j:
  # A1 is set to be a ConsoleAppender.
#  appender:
#    A1: org.apache.log4j.ConsoleAppender
#    A1.layout: org.apache.log4j.PatternLayout
#    A1.layout.ConversionPattern: '%-4r %-5p %c - %m%n'
  debug: true
  logger:
    org:
      mybatis:
        # MBG logging configuration...
        generator: DEBUG
  # Set root logger
  rootLogger: DEBUG, stdout

spring:
  profiles:
    active: dev
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    password: 1234
    platform: postgresql
    username: rssadmin
  http:
    encoding:
      charset:    UTF-8
#  mvc:
#    view:
#      prefix:     /jsp/
#      suffix:     .jsp

server:
  tomcat:
    uri-encoding: UTF-8

rssportal:
  vftp:
    directory:
      request: /LOG/VFTP/Requests
    #objectlistfile: /usr/local/canon/esp/CanonFileService/definitions/ObjectList.xml

  # 'purger' is for cleaning up files that the app has already used in local file system.
  purger:
    # on every downloading files processing, the app uses local cache to keep files temporary.
    # 'download-cache' configuration is to clean this cache up.
    download-cache:
      min-size: 10 # gigabytes
      min-percent: 30
      interval: 1800 # seconds
      keeping-period: 24 # hours
    # 'collect-plan' cleans up files that has completed downloading of auto-collection.
    collect-plan:
      min-size: 10 # gigabytes
      min-percent: 30
      interval: 3600 # seconds
      keeping-period: 24 # hours
    # `file-downloader` cleans up an output directory of downloading processing.
    file-downloader:
      min-size: 10 # gigabytes
      min-percent: 30
      interval: 3600 # seconds

---
spring:
  profiles: dev
  datasource:
    # CKBS [set ip address]
    url: jdbc:postgresql://10.1.31.237:5432/rssdb
  # Hot reload
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false


rssportal:
  property:
    constructdisplay: devTemp/ConstructDisplay.xml
  vftp:
    objectlistfile: devTemp/ObjectList.xml
  collect:
    logBase: planroot
    cacheBase: downloadcache
    resultBase: zipa
  file-collect-service:
    addr: 10.1.31.237
    retry: 1 # retry count
    retry-interval: 100 # interval between each retry

logging:
  file:
    name: ./logs/rssportal.log
    max-size: 100MB
    max-history: 7

---
spring:
  profiles: release
  datasource:
    # CKBS [set ip address]
    url: jdbc:postgresql://localhost/rssdb
rssportal:
  property:
    constructdisplay: /usr/local/canon/esp/CanonFileService/definitions/ConstructDisplay.xml
  vftp:
    objectlistfile: /usr/local/canon/esp/CanonFileService/definitions/ObjectList.xml
  collect:
    logBase: /LOG/autocollect
    cacheBase: /LOG/cache
    resultBase: /LOG/zip
  file-collect-service:
    addr: localhost
    retry: 1 # retry count
    retry-interval: 100 # interval between each retry(msec)

logging:
  file:
    name: /LOG/rssportal/rssportal.log
    max-size: 100MB
    max-history: 7
