export const PAGE_MOVE = "/rss/move";
export const PAGE_LOGIN = "/rss/login";
export const PAGE_MANUAL = "/rss/manual";
export const PAGE_AUTO = "/rss/auto";
export const PAGE_AUTO_PLAN_ADD = "/rss/auto/plan/add";
export const PAGE_AUTO_PLAN_EDIT = "/rss/auto/plan/edit";
export const PAGE_AUTO_STATUS = "/rss/auto/status";
export const PAGE_AUTO_DOWNLOAD = "/rss/auto/download";
export const PAGE_ADMIN = "/rss/admin";
export const GO_PAGE_AUTO_PLAN_ADD = "?target=" + PAGE_AUTO_PLAN_ADD;
export const GO_PAGE_AUTO_PLAN_EDIT = "?target=" + PAGE_AUTO_PLAN_EDIT;
export const GO_PAGE_AUTO_STATUS = "?target=" + PAGE_AUTO_STATUS;
export const GO_PAGE_MANUAL = "?target=" + PAGE_MANUAL;
