export const PAGE_LOGIN = "/rss/login";
export const PAGE_MANUAL = "/rss/manual";
export const PAGE_AUTO = "/rss/auto";
export const PAGE_AUTO_PLAN = "/rss/auto/plan";
export const PAGE_AUTO_PLAN_ADD = "/rss/auto/plan?mode=add";
export const PAGE_AUTO_PLAN_EDIT = "/rss/auto/plan?mode=edit";
export const PAGE_AUTO_STATUS = "/rss/auto/status";
export const PAGE_AUTO_DOWNLOAD = "/rss/auto/download";
export const PAGE_ADMIN = "/rss/admin";
